import { getYearsOfExperience } from '@/i18n/common';

export const en = {
	Description: `I am Ander González González better known as AnderCMD, Full Stack Software Engineer passionate with +<span class="experience-years-count">${getYearsOfExperience('en')}</span> of experience, expert in web development.`,

	'Nav.Index': 'Home',
	'Nav.About': 'Experience',
	'Nav.Posts': 'Posts',
	'Nav.Projects': 'Projects',
	'Nav.Certificates': 'Certificates',
	'Nav.Contact': 'Contact',
	'Nav.OpenMenu': 'Open menu',

	'Footer.Copyright': '© All rights reserved',
	'Footer.Privacy': 'Privacy Policy',
	'Footer.Terms': 'Terms and Conditions',

	'Legal.LastUpdated': 'Last updated',
	'Legal.BackHome': 'Back to home',

	'Legal.Privacy.Title': 'Privacy Policy',
	'Legal.Privacy.SeoDescription':
		"Privacy policy for Ander González's (AnderCMD) portfolio: what data is collected, how it is used, and how to exercise your rights.",
	'Legal.Privacy.Description':
		'How your personal information is collected, used, and protected when you visit this website.',
	'Legal.Privacy.Section.1.Title': '1. Data controller',
	'Legal.Privacy.Section.1.Body':
		'Ander González González (AnderCMD) is the controller responsible for the personal data collected through this website (andercmd.dev), based in Mexico, contact email andercmd@outlook.com.',
	'Legal.Privacy.Section.2.Title': '2. Personal data we collect',
	'Legal.Privacy.Section.2.Body':
		"This site does not have contact forms that send data to our own server: the links in the contact section redirect you to third-party services (email, LinkedIn, GitHub, X/Twitter, WhatsApp) where you decide what information to share directly with those services. Only the administration area (internal, restricted use) processes access credentials, and the link shortener logs the links created and their usage date, without linking them to visitors' personal data.",
	'Legal.Privacy.Section.3.Title': '3. Purpose of data processing',
	'Legal.Privacy.Section.3.Body':
		'Technical data generated by your browsing (e.g., hosting server logs) is used solely to keep the site available, secure, and functioning correctly, and to diagnose errors. It is not used for advertising purposes nor sold or transferred to third parties.',
	'Legal.Privacy.Section.4.Title': '4. Cookies and local storage',
	'Legal.Privacy.Section.4.Body':
		"This site uses the browser's local storage (localStorage) solely to remember your light/dark mode preference. No tracking, advertising, or third-party analytics cookies are used. You can clear this information at any time from your browser settings.",
	'Legal.Privacy.Section.5.Title': '5. Sharing information with third parties',
	'Legal.Privacy.Section.5.Body':
		'We do not share, sell, or transfer personal data to third parties. The site is hosted on Hostinger and uses external services such as Font Awesome (icons) and social networks (LinkedIn, GitHub, X); their own privacy policies apply when you interact with those services.',
	'Legal.Privacy.Section.6.Title': '6. Your rights and how to exercise them',
	'Legal.Privacy.Section.6.Body':
		'If you ever share personal data with us directly (for example, by email), you have the right to access, rectify, cancel, or object to the processing of that data. To exercise these rights, write to andercmd@outlook.com stating your request.',
	'Legal.Privacy.Section.7.Title': '7. Information security',
	'Legal.Privacy.Section.7.Body':
		'Reasonable security measures are in place (HTTPS connection, security headers, and restricted access to admin panels) to protect information against unauthorized access, loss, or alteration.',
	'Legal.Privacy.Section.8.Title': '8. Changes to this policy',
	'Legal.Privacy.Section.8.Body':
		'This privacy policy may be updated periodically to reflect changes to the site or applicable regulations. The date of the last update is shown at the top of this page.',
	'Legal.Privacy.Section.9.Title': '9. Contact',
	'Legal.Privacy.Section.9.Body':
		'For questions or comments about this privacy policy, you can reach us at andercmd@outlook.com.',

	'Legal.Terms.Title': 'Terms and Conditions',
	'Legal.Terms.SeoDescription':
		"Terms and conditions of use for Ander González's (AnderCMD) portfolio: intellectual property, site usage, and limitation of liability.",
	'Legal.Terms.Description': 'Conditions governing access to and use of this website.',
	'Legal.Terms.Section.1.Title': '1. Acceptance of terms',
	'Legal.Terms.Section.1.Body':
		'By accessing and using this website (andercmd.dev), you accept these Terms and Conditions. If you do not agree with any of them, please do not continue using the site.',
	'Legal.Terms.Section.2.Title': '2. Use of the website',
	'Legal.Terms.Section.2.Body':
		'This site is for informational purposes: showcasing the professional experience, projects, and certificates of Ander González González. Use of the site for unlawful purposes, attempting to compromise its security, or accessing administrative sections without authorization is prohibited.',
	'Legal.Terms.Section.3.Title': '3. Intellectual property',
	'Legal.Terms.Section.3.Body':
		"This project's source code is available under the Apache 2.0 License on its GitHub repository. Personal content (biographical text, images, logos, projects, and certificates shown) is the property of Ander González González and may not be reproduced without permission, except as allowed by the code's license.",
	'Legal.Terms.Section.4.Title': '4. Links to third-party sites',
	'Legal.Terms.Section.4.Body':
		'This site includes links to third-party platforms (LinkedIn, GitHub, X/Twitter, WhatsApp, project repositories, among others). We have no control over the content or policies of those sites and are not responsible for them.',
	'Legal.Terms.Section.5.Title': '5. Limitation of liability',
	'Legal.Terms.Section.5.Body':
		'The site is provided "as is," without warranties of any kind. We are not liable for damages arising from the use or inability to use the site, nor for service interruptions.',
	'Legal.Terms.Section.6.Title': '6. Privacy',
	'Legal.Terms.Section.6.Body':
		'The processing of personal data is governed by our Privacy Policy, which forms an integral part of these Terms and Conditions.',
	'Legal.Terms.Section.7.Title': '7. Changes to these terms',
	'Legal.Terms.Section.7.Body':
		'We reserve the right to modify these Terms and Conditions at any time. Changes will take effect upon publication on this same page.',
	'Legal.Terms.Section.8.Title': '8. Governing law and jurisdiction',
	'Legal.Terms.Section.8.Body':
		'These Terms and Conditions are governed by the laws of the United Mexican States. Any dispute shall be submitted to the competent courts accordingly.',
	'Legal.Terms.Section.9.Title': '9. Contact',
	'Legal.Terms.Section.9.Body':
		'For questions or comments about these Terms and Conditions, you can reach us at andercmd@outlook.com.',

	'Error.Title.400': 'Error 400',
	'Error.Message.400': 'Bad Request. The server could not understand the request.',
	'Error.Title.401': 'Error 401',
	'Error.Message.401': 'Unauthorized. You must log in to access this page.',
	'Error.Title.403': 'Error 403',
	'Error.Message.403': 'Forbidden. You do not have permission to access.',
	'Error.Title.404': 'Error 404',
	'Error.Message.404': 'Sorry, the page you are looking for does not exist.',
	'Error.Title.500': 'Error 500',
	'Error.Message.500': 'Internal Error. Something went wrong on our end.',
	'Error.Title.502': 'Error 502',
	'Error.Message.502': 'Bad Gateway. The server received an invalid response.',
	'Error.Title.503': 'Error 503',
	'Error.Message.503': 'Service Unavailable. The server is temporarily out of service.',
	'Error.Button.404': 'Go back to home',
	'Error.Button.Generic': 'Go back to home',

	'Experience.Title': 'Hi! I am Ander González González 👋🏻',
	'Experience.Subtitle': 'Software Engineer',
	'Experience.Description': `Full Stack Software Engineer with over <span class="experience-years-count">${getYearsOfExperience('en')}</span> of experience in designing scalable and optimized web applications. Expert in modern technologies such as React, Astro, PostgreSQL, and MongoDB, with strong leadership, problem-solving skills, and development of innovative solutions. Passionate about continuous learning and strategically adding value to every project.`,
	'Experience.SeoDescription': `Full Stack Software Engineer with over <span class="experience-years-count">${getYearsOfExperience('en')}</span> of experience in designing scalable and optimized web applications. Expert in modern technologies such as React, Astro, PostgreSQL, and MongoDB, with strong leadership, problem-solving skills, and development of innovative solutions. Passionate about continuous learning and strategically adding value to every project.`,
	'Experience.CV': 'Download CV',
	'Experience.CV.Link': '/Download/CV/CV_Ander_Gonzalez_Gonzalez_EN_Web.pdf',

	'Contact.Title': 'Contact me',
	'Contact.Subtitle': 'Do you want to work with me? Contact me!',
	'Contact.Description':
		'If you have any questions or want to work with me, do not hesitate to contact me. I will be happy to help you!',
	'Contact.Form.Name': 'Name',
	'Contact.Form.Email': 'Email',
	'Contact.Form.Message': 'Message',
	'Contact.Form.Message.Placeholder': 'Write your message here...',

	'Contact.Form.Submit': 'Send',
	'Contact.Info.ResponseTime.Title': 'Response Time',
	'Contact.Info.ResponseTime.Description': 'I usually respond within 24-48 hours',
	'Contact.Info.Availability.Title': 'Availability',
	'Contact.Info.Availability.Description': 'Open to new projects and collaborations',
	'Contact.Info.Location.Title': 'Location',
	'Contact.Info.Location.Description': 'Remote work from any timezone',

	'Card.MetaTitle': 'Ander González · Contact Card',
	'Card.Name': 'Eng. Ander González',
	'Card.Handle': '@AnderCMD',
	'Card.JobTitle': 'Full Stack Software Engineer',
	'Card.Call': 'Call',
	'Card.WhatsApp': 'WhatsApp',
	'Card.Email': 'Email',
	'Card.Portfolio': 'Portfolio',
	'Card.ScanToShare': 'Scan to share this card',
	'Card.SaveContact': 'Save contact',
	'Card.BackHome': 'Back to home',

	'Common.Loading': 'Loading...',
	'Common.ViewMore': 'View more',
	'Common.ViewLess': 'View less',
	'Common.ScrollToTop': 'Scroll to top',
	'Common.SkipToContent': 'Skip to main content',

	'Tech.Title': 'Technologies',
	'Tech.Description': 'Technologies I use in my projects and work.',

	'Projects.Nav.AllCategories': 'All categories',
	'Projects.Nav.Web': 'Web',
	'Projects.Nav.Mobile': 'Mobile',
	'Projects.Nav.Desktop': 'Desktop',
	'Projects.Nav.Other': 'Other',
	'Projects.Title': 'Projects',
	'Projects.Subtitle': 'Some of my projects',
	'Projects.Description': 'Here are some of the projects I have worked on. You can see more on my GitHub profile.',
	'Projects.ViewCode': 'View code',
	'Projects.VisitProject': 'Visit project',
	'Projects.Download': 'Download',
	'Projects.CTA.Title': 'Have a project in mind?',
	'Projects.CTA.Description':
		"Let's work together to make it a reality. I'm always open to new opportunities and collaborations.",
	'Projects.CTA.Contact': 'Contact',
	'Projects.CTA.ViewGitHub': 'View GitHub',
	'Projects.Sort.ByStatus': 'By Status',
	'Projects.Sort.ByDate': 'By Date',

	'Projects.Title.1': 'Horoscope',
	'Projects.Description.1': 'Discover your zodiac sign based on your birth date.',

	'Projects.Title.2': 'Calculator',
	'Projects.Description.2': 'Simple calculator for basic operations with a graphical interface.',

	'Projects.Title.3': 'GPT - Local',
	'Projects.Description.3': 'AI chatbot powered by the Llama 3 model.',

	'Projects.Title.4': 'AMEDigital A.C.',
	'Projects.Description.4': 'Corporate website for AMEDigital A.C.',

	'Projects.Title.5': 'Diagnostico Moderno',
	'Projects.Description.5': 'Corporate medical website for Diagnostico Moderno.',

	'Projects.Title.7': 'EcologiX Environmental Monitoring System',
	'Projects.Description.7': 'EcologiX environmental monitoring system with Arduino sensor connectivity.',

	'Projects.Title.8': 'Flappy Bat',
	'Projects.Description.8': 'Flappy Bat game for Android devices developed with Unity, inspired by Flappy Bird.',

	'Projects.Title.9': 'Technical Challenge Chat Bot',
	'Projects.Description.9': 'Technical challenge for Intellion: chatbot with predefined responses.',

	'Projects.Title.10': 'Frontend-Mentor Challenges',
	'Projects.Description.10': 'Frontend-Mentor challenges to enhance my web development skills.',

	'Projects.Title.11': 'Repair Windows Script',
	'Projects.Description.11': 'Executable to repair files on Windows 10 and 11.',

	'Projects.Title.12': 'TasksFlow',
	'Projects.Description.12':
		'Task management system to create, edit, and delete tasks, assign due dates and priorities.',

	'Projects.Title.13': 'SETI - Point of Sale System',
	'Projects.Description.13': 'Point of sale system (POS) for Sistemas Empresariales en T.I.',

	'Projects.Title.14': 'Resser Tecnologias SA de CV (SaaS & ERP)',
	'Projects.Description.14':
		'Resser Tecnologías SA de CV platform (SaaS and ERP) for administrative management and external monitoring.',
	'Projects.Title.15': 'Sistemas Empresariales en T.I. (SETI)',
	'Projects.Description.15': 'Corporate website for Sistemas Empresariales en T.I. (SETI).',

	'WorkExperience.Title': 'Work Experience',
	'WorkExperience.Description':
		'Here are some of the companies where I have worked and the projects I have developed.',
	'WorkExperience.Active': 'Latest',
	'WorkExperience.ReleaseDate': 'Date: ',
	'WorkExperience.Visit': 'Visit',
	'WorkExperience.Month': 'Month',
	'WorkExperience.Months': 'Months',

	'WorkExperience.Companies.Position.5': 'Software & QA Automation Engineer',
	'WorkExperience.Companies.Description.5':
		'Responsible for designing automated scripts, executing and analyzing tests, as well as documenting and preparing result reports, contributing to the improvement of software quality and reliability.\n\nSome of the technologies used are: (Java, Git, SQL, Jira, Selenium)',

	'WorkExperience.Companies.Position.4': 'Junior Full Stack Software Engineer',
	'WorkExperience.Companies.Description.4':
		'Participation in the development of a business management platform, including the creation of modules under the SaaS model, working with Agile Scrum methodology and collaborating in the migration of obsolete technologies to modern technologies.\n\nSome of the technologies used are: (C#, .NET 8, TypeScript, React, SQL Server, Azure, Git)',

	'WorkExperience.Companies.Position.3': 'Full Stack Software Engineer',
	'WorkExperience.Companies.Description.3':
		'Participation in the development of a business website, implementation of DevOps practices, management and contracting of licenses, creation of cloud infrastructure, corporate email administration, as well as support and maintenance of the systems.\n\nSome of the technologies used are: (Astro, React, ExpressJS, MongoDB, JavaScript, TypeScript, TailwindCSS, Hostinger)',

	'WorkExperience.Companies.Position.2': 'Full Stack Software Engineer (Freelance)',
	'WorkExperience.Companies.Description.2':
		'Participation in the development of websites for companies in the medical sector, creation of cloud infrastructure, corporate email administration, and SEO optimization.\n\nSome of the technologies used are: (Astro, React, ExpressJS, MongoDB, JavaScript, TypeScript, TailwindCSS, Hostinger)',

	'WorkExperience.Companies.Position.1': 'Software Engineering Intern (Internship I & II)',
	'WorkExperience.Companies.Description.1':
		'Collaboration in the development of web applications, participation in artificial intelligence projects and implementation of improvements in existing systems.\n\nSome of the technologies used are: (React, CSS, HTML, JavaScript, Python, AWS)',
	'Projects.Title.16': 'Folio Generator',
	'Projects.Description.16':
		'A robust and flexible library designed to generate sequential alphanumeric codes (folios). Supports automatic padding, custom separators, and is fully Type-safe. Available in JS, TS, and Python.',
	'Projects.Title.17': 'Vigilant',
	'Projects.Description.17':
		'Lightweight Windows system tray application that simulates user activity to prevent the system from going into sleep mode or changing its status to "Away".',
	'Projects.Title.18': 'AutoSwitchMonitor',
	'Projects.Description.18':
		"Automatically switches your monitor's video input (DDC/CI) when you move a USB KVM switch between PCs, with configurable global hotkeys. Single Go binary for Windows and macOS.",
	'Projects.Status.OutOfService': 'Out of Service',
	'Projects.Status.Unmaintained': 'Unmaintained',
	'Projects.Status.Active': 'Active',
	'Projects.Status.Delivered': 'Delivered',

	'Certificates.Title': 'Certificates',
	'Certificates.Description':
		'Courses, diplomas, and recognitions I have earned throughout my journey as a Software Engineer.',
	'Certificates.SeoDescription':
		'Certificates, courses, and diplomas earned by Ander González (AnderCMD) on platforms such as Platzi, HackerRank, Fundación Carlos Slim, and more.',
	'Certificates.ViewCertificate': 'View certificate',

	'Certificates.Items.Title.1': 'JavaScript Fundamentals',
	'Certificates.Items.Title.2': 'Problem Solving (Intermediate)',
	'Certificates.Items.Title.3': 'C# (Basic)',
	'Certificates.Items.Title.4': 'Node.js (Basic)',
	'Certificates.Items.Title.5': 'Python (Basic)',
	'Certificates.Items.Title.6': 'JavaScript (Intermediate)',
	'Certificates.Items.Title.7': 'Software Engineer',
	'Certificates.Items.Title.8': 'Problem Solving (Basic)',
	'Certificates.Items.Title.9': 'JavaScript (Basic)',
	'Certificates.Items.Title.10': 'CSS (Basic)',
	'Certificates.Items.Title.11': 'Web Development School',
	'Certificates.Items.Title.12': 'Pre-Work: Work Environment Setup',
	'Certificates.Items.Title.13': 'Backend with NestJS',
	'Certificates.Items.Title.14': 'Incubation & Entrepreneurship Program — Juventudes con Idea',
	'Certificates.Items.Title.15': 'Introduction to Emerging Technologies: 2024 Edition',
	'Certificates.Items.Title.16': 'Full Stack Developer with JavaScript',
	'Certificates.Items.Title.17': 'Professional Git & GitHub Course',
	'Certificates.Items.Title.18': 'Development Environment Setup on Linux',
	'Certificates.Items.Title.19': 'Development Environment Setup on macOS',
	'Certificates.Items.Title.20': 'Introduction to Terminal & Command Line',
	'Certificates.Items.Title.21': 'Development Environment Setup on Windows',
	'Certificates.Items.Title.22': 'Introduction to React Native',
	'Certificates.Items.Title.23': 'Hack AI — Día de la Mentefactura 2024',
	'Certificates.Items.Title.24': 'Día de la Mentefactura (DMF24)',
	'Certificates.Items.Title.25': 'Fundamentals of Artificial Intelligence',
	'Certificates.Items.Title.26': 'Comprehensive Web Development',
	'Certificates.Items.Title.27': 'SIGA 2023 Award — Digital Public Innovation',
	'Certificates.Items.Title.28': 'Valores del Ser',
	'Certificates.Items.Title.29': 'Web Assistant',
} as const;
